### ISSUE TITLE
YuzuModDownloader not downloading from theboy181 and crashing when unpacking from HolographicWings

### ISSUE THREAD

**Issue by ghost** [amakvana/YuzuModDownloader#25] opened 2023-07-13 20:26 UTC
YuzuModDownloader not loading anything from theboy181 and crashing when downloading from HolographicWings.

1. Open YuzuModDownloader
2. Click on Download
3. Only Downloading from the first Github

**Expected behavior**
It downloading every Mod available for every Game installed

**Screenshots**
(https://youtu.be/zm2eK2WZE2Q)

**Desktop/Laptop (please complete the following information):**
 - OS: Windows 10
 - Yuzu Version 1495
 - Yuzu Standalone or Installed? I guess installed??? It's in Roaming

**Additional context**
My AdBlocker AdGuard doesnt change anything if enabled or disabled.

**Comment by amakvana** [comment] 2023-07-13 20:56
Thanks for the video, that helps alot! Would you be able to keep it online until this is sorted? 

For theboy181's repo, you'll need to make sure your games match up to the specific Game ID's and also ensure the version also matches, as his repo only contains mods for certain versions of games listed. 

I will check the TOTK mods and see what's playing up with them

**Comment by PhynixAbyss** [comment] 2023-07-13 21:02
But i have atleast 1 Game exactly for theboy181 with Bayonetta 3 and it still does not even download it for this Game.

Honestly weird too, that you need the perfect exact same thing for it to work.

Bayonetta 3
Game ID: 01004A4010FEA000
Update Version 1.2.0

**Comment by amakvana** [comment] 2023-07-13 21:11
> Bayonetta 3 Game ID: 01004A4010FEA000 Update Version 1.2.0
> 
> The Last time: #23 it worked fine after he made the 1.2.0 Version available on his Github.
> 
> And it should work now too, but it doesnt for some reason.

I'll try reproducing the error you're getting with this ^ 

However, I am struggling to reproduce the error you're getting with the TOTK repo, same game version, same title ID. See gif below:

![ymd-totk-112](https://github.com/amakvana/YuzuModDownloader/assets/66264136/d73fa3d5-1ab0-4175-b59b-1b21d961dae2)

**Comment by PhynixAbyss** [comment] 2023-07-13 21:15
Still crashes

**Comment by amakvana** [comment] 2023-07-13 21:18
Strange! Could you provide me with the installation path of yuzu on your machine? Along with where the "mod load root" path points to?

**Comment by PhynixAbyss** [comment] 2023-07-13 21:19
C:\Users\Phynix\AppData\Roaming\yuzu
F:\Games\Emulator\Switch\Yuzu\Data\load

**Comment by amakvana** [comment] 2023-07-13 21:23
Have you got many mods populated within the `\load\` folder already? I'm thinking potentially deleting the folder and letting Yuzu remake them, before retrying to download the Mods.

Have you placed YuzuModDownloader within `C:\Users\Phynix\AppData\Roaming\yuzu` too, right?

**Comment by PhynixAbyss** [comment] 2023-07-13 21:24
I already tried deleting everything inside load multiple times and no i did not put it inside the installation Folder, cause the first Github thingy works everywhere i put YuzuModDownloader, but sure, i can try.

**Comment by amakvana** [comment] 2023-07-13 21:34
Okay, what's inside the following folder?

`F:\Games\Emulator\Switch\Yuzu\Data\load\0100F2C0115B6000`

**Comment by PhynixAbyss** [comment] 2023-07-13 21:37
Nothing

**Comment by amakvana** [comment] 2023-07-13 21:42
There should be the `TOTK-Mods-Collection-1.1.2.7z` archive since it crashed midway through. Are you alright to upload your `qt-config.ini` file onto here? It'll be located in `C:\Users\Phynix\AppData\Roaming\yuzu\config`

**Comment by PhynixAbyss** [comment] 2023-07-13 21:47
YuzuModDownloader automatically deletes thos files or not?

If not because it crashes, then i might have deleted it on my own.

[qt-config.zip](https://github.com/amakvana/YuzuModDownloader/files/12044688/qt-config.zip)

**Comment by amakvana** [comment] 2023-07-13 21:47
> YuzuModDownloader automatically deletes thos files or not?
> 
> If not because it crashes, then i might have deleted it on my own.
> 
> [qt-config.zip](https://github.com/amakvana/YuzuModDownloader/files/12044688/qt-config.zip)

It'll delete the archive once everything has been successfully extracted

**Comment by amakvana** [comment] 2023-07-13 22:03
Okay try this for me:

1. Close both Yuzu and YuzuModDownloader - make sure no tasks containing the word "yuzu" appear inside Task Manager 
2. Download the `qt-config.zip` archive attached below
3. Extract the `qt-config.zip` archive somewhere 
4. Copy the `qt-config.ini` file you have downloaded, then paste and override the file inside `C:\Users\Phynix\AppData\Roaming\yuzu\config`. When prompted to override, confirm it
5. Launch Yuzu then close Yuzu
6. Open YuzuModDownloader and try again 

[qt-config.zip](https://github.com/amakvana/YuzuModDownloader/files/12044769/qt-config.zip)

Let me know how you get on

**Comment by PhynixAbyss** [comment] 2023-07-13 22:26
theboy181 didn't work still, but HolographicWings now did unpack for no reason at all.

**Comment by PhynixAbyss** [comment] 2023-07-14 11:39
HolographicWings did Unpack for no reason at all now, after using your qt-config.ini, but theboy181 still does not find any Game i have installed, even tho i still have the same Bayonetta 3 Game ID and Version Number like the last time.

**Comment by amakvana** [comment] 2023-07-14 18:24
Update - the way GitHub now loads the mods into the browser is through JS via React. I don't think HtmlAgilityPack is capable of scraping this way. So I will look into rewriting this with Selenium instead. Once I have a working solution, I will post back in here

**Comment by PhynixAbyss** [comment] 2023-07-15 10:51
Well, thank you for helping, finding stuff out and even trying to fix things that consume time of your freetime.

Very appreciated and see you until then again.

**Comment by CozMedic** [comment] 2023-09-26 19:30
Apologies, I know this is already being worked on & I appreciate your time looking into & resolving the issue. I just wanted to +1 that I'm experiencing the same issue. Seems unlikely, but in case it's of any use, I'm happy to provide my qt-config.ini or paths as well.

Thanks again.

**Comment by amakvana** [comment] 2024-02-07 15:10
Closed - Fixed in v1.4.1.0
https://github.com/amakvana/YuzuModDownloader/releases/latest

**Closed by amakvana** 2024-02-07 15:10 UTC
Labels: bug
